export const commonSupplements = [
  // Vitamins
  { name: 'Vitamin A', dosage: '900 mcg RAE (men), 700 mcg RAE (women)' },
  { name: 'Vitamin B1 (Thiamine)', dosage: '1.2 mg (men), 1.1 mg (women)' },
  { name: 'Vitamin B2 (Riboflavin)', dosage: '1.3 mg (men), 1.1 mg (women)' },
  { name: 'Vitamin B3 (Niacin)', dosage: '16 mg NE (men), 14 mg NE (women)' },
  { name: 'Vitamin B5 (Pantothenic Acid)', dosage: '5 mg' },
  { name: 'Vitamin B6 (Pyridoxine)', dosage: '1.3-1.7 mg' },
  { name: 'Vitamin B7 (Biotin)', dosage: '30 mcg' },
  { name: 'Vitamin B9 (Folate/Folic Acid)', dosage: '400 mcg DFE' },
  { name: 'Vitamin B12 (Cobalamin)', dosage: '2.4 mcg' },
  { name: 'Vitamin C (Ascorbic Acid)', dosage: '90 mg (men), 75 mg (women)' },
  { name: 'Vitamin D (Cholecalciferol/Ergocalciferol)', dosage: '600-800 IU (15-20 mcg)' },
  { name: 'Vitamin E (Tocopherol)', dosage: '15 mg' },
  { name: 'Vitamin K (Phylloquinone/Menaquinone)', dosage: '120 mcg (men), 90 mcg (women)' },

  // Minerals
  { name: 'Calcium', dosage: '1000-1300 mg' },
  { name: 'Chromium', dosage: '35 mcg (men), 25 mcg (women)' },
  { name: 'Copper', dosage: '900 mcg' },
  { name: 'Iodine', dosage: '150 mcg' },
  { name: 'Iron', dosage: '8 mg (men), 18 mg (women pre-menopause), 8 mg (women post-menopause)' },
  { name: 'Magnesium', dosage: '400-420 mg (men), 310-320 mg (women)' },
  { name: 'Manganese', dosage: '2.3 mg (men), 1.8 mg (women)' },
  { name: 'Molybdenum', dosage: '45 mcg' },
  { name: 'Phosphorus', dosage: '700 mg' },
  { name: 'Potassium', dosage: '3400 mg (men), 2600 mg (women)' },
  { name: 'Selenium', dosage: '55 mcg' },
  { name: 'Sodium', dosage: '< 2300 mg' },
  { name: 'Zinc', dosage: '11 mg (men), 8 mg (women)' },
  { name: 'Boron', dosage: '1-3 mg (No official RDA)' },
  { name: 'Silicon', dosage: '10-25 mg (No official RDA)' },

  // Other Common Supplements
  { name: 'Omega-3 Fatty Acids (Fish Oil)', dosage: '1000-2000 mg EPA+DHA' },
  { name: 'Probiotics', dosage: 'Varies (e.g., 1-50 billion CFU)' },
  { name: 'Coenzyme Q10 (CoQ10)', dosage: '100-200 mg' },
  { name: 'Glucosamine', dosage: '1500 mg' },
  { name: 'Chondroitin', dosage: '800-1200 mg' },
  { name: 'Melatonin', dosage: '0.5-5 mg' },
  { name: 'Ginseng', dosage: '200-400 mg Panax extract' },
  { name: 'Ginkgo Biloba', dosage: '120-240 mg extract' },
  { name: 'Turmeric (Curcumin)', dosage: '500-1000 mg extract' },
  { name: 'Creatine', dosage: '3-5 g (maintenance)' },
  { name: 'Protein Powder (Whey, Casein, etc.)', dosage: '20-30 g per serving' },
  { name: 'Fiber (Psyllium Husk)', dosage: '5-10 g' },
  { name: 'Ashwagandha', dosage: '300-600 mg extract' },
  { name: 'Elderberry', dosage: '500-1000 mg extract' },
  { name: 'Echinacea', dosage: '300-500 mg extract' },
  { name: 'Valerian Root', dosage: '300-600 mg extract before bed' },
  { name: 'St. John\'s Wort', dosage: '300 mg extract 3x daily' },
  { name: 'Milk Thistle', dosage: '150-300 mg silymarin' },
  { name: 'Saw Palmetto', dosage: '160-320 mg extract' },
  { name: 'L-Theanine', dosage: '100-200 mg' },
  { name: '5-HTP', dosage: '50-100 mg' },
  { name: 'Beta-Alanine', dosage: '2-5 g' },
  { name: 'BCAAs', dosage: '5-10 g' },
  { name: 'Collagen', dosage: '10-20 g' },
  { name: 'Hyaluronic Acid', dosage: '100-200 mg' },
  { name: 'Resveratrol', dosage: '100-500 mg' },
  { name: 'NAC (N-Acetyl Cysteine)', dosage: '600-1800 mg' },
  { name: 'L-Carnitine', dosage: '500-2000 mg' },
  { name: 'Rhodiola Rosea', dosage: '200-600 mg extract' },
  { name: 'Alpha-Lipoic Acid', dosage: '300-600 mg' },
  { name: 'Green Tea Extract', dosage: '250-500 mg EGCG' },
  { name: 'Berberine', dosage: '500 mg 2-3x daily' },
  { name: 'DHEA', dosage: '25-50 mg (consult doctor)' },
  { name: 'Astaxanthin', dosage: '4-12 mg' },
  { name: 'L-Tyrosine', dosage: '500-2000 mg' },
  { name: 'Inositol', dosage: '500-4000 mg (based on goal)' }
];